# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoCICD' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for DemoCICD
pod 'AppCenter'


  target 'DemoCICDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoCICDUITests' do
    # Pods for testing
  end

end
